systems:
  - darwin/amd64
  - darwin/arm64
  - linux/amd64
  - windows/amd64
dependencies:
  action-doc:
    template: action-doc
    vars:
      version: 0.4.0
  gh:
    template: origin#gh
    vars:
      version: 2.29.0
  jq:
    template: origin#jq
    vars:
      version: "1.6"
  release-train:
    template: release-train
    vars:
      version: 0.1.0
  shellcheck:
    template: origin#shellcheck
    vars:
      version: 0.9.0
  shfmt:
    template: origin#shfmt
    vars:
      version: 3.6.0
templates:
  action-doc:
    homepage: https://github.com/WillAbides/action-doc
    description: generate markdown documentation based on an action's action.yml
    url: https://github.com/WillAbides/action-doc/releases/download/v{{.version}}/action-doc_{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: action-doc{{.archivePathSuffix}}
    bin: action-doc
    vars:
      archivePathSuffix: ""
      urlSuffix: .tar.gz
    substitutions:
      arch:
        arm64: amd64
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/amd64
    required_vars:
      - version
  origin#gh:
    homepage: https://github.com/cli/cli
    description: GitHub’s official command line tool
    url: https://github.com/cli/cli/releases/download/v{{.version}}/gh_{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: gh_{{.version}}_{{.os}}_{{.arch}}/bin/gh{{.archivePathSuffix}}
    bin: gh
    vars:
      archivePathSuffix: ""
      urlSuffix: .zip
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          archive_path: bin/gh{{.archivePathSuffix}}
          vars:
            archivePathSuffix: .exe
      - matcher:
          os:
            - linux
        dependency:
          vars:
            urlSuffix: .tar.gz
      - matcher:
          os:
            - darwin
          version:
            - < 2.28.0
        dependency:
          vars:
            urlSuffix: .tar.gz
    substitutions:
      os:
        darwin: macOS
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm64
      - windows/386
      - windows/amd64
      - windows/arm64
    required_vars:
      - version
  origin#jq:
    homepage: https://github.com/stedolan/jq
    description: Command-line JSON processor
    url: https://github.com/stedolan/jq/releases/download/jq-{{.version}}/jq-{{.os}}{{.arch}}{{.extension}}
    archive_path: jq-{{.os}}{{.arch}}{{.extension}}
    bin: jq
    vars:
      extension: ""
    overrides:
      - matcher:
          arch:
            - amd64
            - arm64
          os:
            - darwin
        dependency:
          url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
          archive_path: jq-osx-amd64
      - matcher:
          os:
            - windows
        dependency:
          vars:
            extension: .exe
    substitutions:
      arch:
        "386": "32"
        amd64: "64"
      os:
        windows: win
    systems:
      - linux/386
      - linux/amd64
      - darwin/amd64
      - darwin/arm64
      - windows/386
      - windows/amd64
    required_vars:
      - version
  origin#shellcheck:
    homepage: https://www.shellcheck.net
    description: ShellCheck, a static analysis tool for shell scripts
    url: https://github.com/koalaman/shellcheck/releases/download/v{{.version}}/shellcheck-v{{.version}}.{{.os}}.{{.arch}}{{.urlSuffix}}
    archive_path: shellcheck-v{{.version}}/shellcheck{{.archivePathSuffix}}
    bin: shellcheck
    vars:
      archivePathSuffix: ""
      urlSuffix: .tar.xz
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          url: https://github.com/koalaman/shellcheck/releases/download/v{{.version}}/shellcheck-v{{.version}}.zip
          archive_path: shellcheck.exe
      - matcher:
          arch:
            - arm64
          os:
            - darwin
        dependency:
          substitutions:
            arch:
              arm64: x86_64
    substitutions:
      arch:
        amd64: x86_64
        arm: armv6hf
        arm64: aarch64
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/amd64
      - linux/arm
      - linux/arm64
      - windows/amd64
    required_vars:
      - version
  origin#shfmt:
    homepage: https://github.com/mvdan/sh
    description: A shell parser, formatter, and interpreter with bash support; includes shfmt
    url: https://github.com/mvdan/sh/releases/download/v{{.version}}/shfmt_v{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: shfmt_v{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    bin: shfmt
    vars:
      archivePathSuffix: ""
      urlSuffix: ""
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          vars:
            urlSuffix: .exe
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm
      - linux/arm64
      - windows/386
      - windows/amd64
    required_vars:
      - version
  release-train:
    homepage: https://github.com/WillAbides/release-train
    url: https://github.com/WillAbides/release-train/releases/download/v{{.version}}/release-train_{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: release-train{{.archivePathSuffix}}
    bin: release-train
    vars:
      archivePathSuffix: ""
      urlSuffix: .tar.gz
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          vars:
            archivePathSuffix: .exe
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/amd64
      - windows/amd64
    required_vars:
      - version
template_sources:
  origin: https://raw.githubusercontent.com/WillAbides/bindown-templates/master/bindown.yml
url_checksums:
  https://github.com/WillAbides/action-doc/releases/download/v0.4.0/action-doc_0.4.0_darwin_amd64.tar.gz: 6fcdd45d6a30bf5d17c27b09725fbd4cea5fef96e635abc82c894156207bf9b8
  https://github.com/WillAbides/action-doc/releases/download/v0.4.0/action-doc_0.4.0_linux_amd64.tar.gz: 7c09a3b9270b4589e11a4f5248e0eb5eb9f5a0126625b5a0675c36554efb76d2
  https://github.com/WillAbides/release-train/releases/download/v0.1.0/release-train_0.1.0_darwin_amd64.tar.gz: 1c231d13c2468d5ab935b16ed162d706ab17c9520546e8c560c249586818c331
  https://github.com/WillAbides/release-train/releases/download/v0.1.0/release-train_0.1.0_darwin_arm64.tar.gz: 6c95a4b330117127e2a9aad4d035ed202216ce8fdde83833e24e47908c7d5c7c
  https://github.com/WillAbides/release-train/releases/download/v0.1.0/release-train_0.1.0_linux_amd64.tar.gz: f567d55930761828f54e6c193887d9934e9ee43b892c503fc15035076d8ca652
  https://github.com/WillAbides/release-train/releases/download/v0.1.0/release-train_0.1.0_windows_amd64.tar.gz: 45d669b83988349f593d32fd35b9d9b686d1f2d5e78f03c0d08c37f6cbca3b6f
  https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_linux_amd64.tar.gz: 9fe05f43a11a7bf8eacf731422452d1997e6708d4160ef0efcb13c103320390e
  https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_macOS_amd64.zip: e116d0f9c310450482cdcd7f4d2d1c7c4cab8d4f025a340260ce3f15329c5145
  https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_macOS_arm64.zip: 38ca9a355376abd1475362cf8b3cacf2a757198fe5fe70349cb1767666abacc6
  https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_windows_amd64.zip: 031eb343ebff6f8cc712d58d79267ee00b0c61b37d6698927161daae895044c6
  https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.darwin.x86_64.tar.xz: 7d3730694707605d6e60cec4efcb79a0632d61babc035aa16cda1b897536acf5
  https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.linux.x86_64.tar.xz: 700324c6dd0ebea0117591c6cc9d7350d9c7c5c287acbad7630fa17b1d4d9e2f
  https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.zip: ae58191b1ea4ffd9e5b15da9134146e636440302ce3e2f46863e8d71c8be1bbb
  https://github.com/mvdan/sh/releases/download/v3.6.0/shfmt_v3.6.0_darwin_amd64: b8c9c025b498e2816b62f0b717f6032e9ab49e725a45b8205f52f66318f17185
  https://github.com/mvdan/sh/releases/download/v3.6.0/shfmt_v3.6.0_darwin_arm64: 633f242246ee0a866c5f5df25cbf61b6af0d5e143555aca32950059cf13d91e0
  https://github.com/mvdan/sh/releases/download/v3.6.0/shfmt_v3.6.0_linux_amd64: 5741a02a641de7e56b8da170e71a97e58050d66a3cf485fb268d6a5a8bb74afb
  https://github.com/mvdan/sh/releases/download/v3.6.0/shfmt_v3.6.0_windows_amd64.exe: 18122d910ba434be366588f37c302c309cde4ca5403f93285254a3cf96839d01
  https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64: af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44
  https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64: 5c0a0a3ea600f302ee458b30317425dd9632d1ad8882259fcaf4e9b868b2b1ef
  https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe: a51d36968dcbdeabb3142c6f5cf9b401a65dc3a095f3144bd0c118d5bb192753
