systems:
  - darwin/amd64
  - darwin/arm64
  - linux/amd64
  - windows/amd64
dependencies:
  gh:
    template: origin#gh
    vars:
      version: 2.29.0
  jq:
    template: origin#jq
    vars:
      version: "1.6"
  semver-next:
    template: origin#semver-next
    vars:
      version: 2.1.0
  semver-prev:
    template: origin#semver-prev
    vars:
      version: 0.0.1
templates:
  origin#gh:
    homepage: https://github.com/cli/cli
    description: GitHub’s official command line tool
    url: https://github.com/cli/cli/releases/download/v{{.version}}/gh_{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: gh_{{.version}}_{{.os}}_{{.arch}}/bin/gh{{.archivePathSuffix}}
    bin: gh
    vars:
      archivePathSuffix: ""
      urlSuffix: .zip
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          archive_path: bin/gh{{.archivePathSuffix}}
          vars:
            archivePathSuffix: .exe
      - matcher:
          os:
            - linux
        dependency:
          vars:
            urlSuffix: .tar.gz
      - matcher:
          os:
            - darwin
          version:
            - < 2.28.0
        dependency:
          vars:
            urlSuffix: .tar.gz
    substitutions:
      os:
        darwin: macOS
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm64
      - windows/386
      - windows/amd64
      - windows/arm64
    required_vars:
      - version
  origin#jq:
    homepage: https://github.com/stedolan/jq
    description: Command-line JSON processor
    url: https://github.com/stedolan/jq/releases/download/jq-{{.version}}/jq-{{.os}}{{.arch}}{{.extension}}
    archive_path: jq-{{.os}}{{.arch}}{{.extension}}
    bin: jq
    vars:
      extension: ""
    overrides:
      - matcher:
          arch:
            - amd64
            - arm64
          os:
            - darwin
        dependency:
          url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
          archive_path: jq-osx-amd64
      - matcher:
          os:
            - windows
        dependency:
          vars:
            extension: .exe
    substitutions:
      arch:
        "386": "32"
        amd64: "64"
      os:
        windows: win
    systems:
      - linux/386
      - linux/amd64
      - darwin/amd64
      - darwin/arm64
      - windows/386
      - windows/amd64
    required_vars:
      - version
  origin#semver-next:
    homepage: https://github.com/WillAbides/semver-next
    url: https://github.com/WillAbides/semver-next/releases/download/v{{.version}}/semver-next_{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: semver-next{{.archivePathSuffix}}
    bin: semver-next
    vars:
      archivePathSuffix: ""
      urlSuffix: .tar.gz
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          vars:
            archivePathSuffix: .exe
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm64
      - windows/386
      - windows/amd64
      - windows/arm64
    required_vars:
      - version
  origin#semver-prev:
    homepage: https://github.com/willabides/semver-prev
    url: https://github.com/WillAbides/semver-prev/releases/download/v{{.version}}/semver-prev_{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: semver-prev{{.archivePathSuffix}}
    bin: semver-prev
    vars:
      archivePathSuffix: ""
      urlSuffix: .tar.gz
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          vars:
            archivePathSuffix: .exe
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm64
      - windows/386
      - windows/amd64
      - windows/arm64
    required_vars:
      - version
template_sources:
  origin: https://raw.githubusercontent.com/WillAbides/bindown-templates/master/bindown.yml
url_checksums:
  https://github.com/WillAbides/semver-next/releases/download/v2.1.0/semver-next_2.1.0_darwin_amd64.tar.gz: eea5854c0d9a2745b4477b41d4e5a94cd27bd04c7c0d39c53f5c8da22753970f
  https://github.com/WillAbides/semver-next/releases/download/v2.1.0/semver-next_2.1.0_darwin_arm64.tar.gz: 4c580e3976ed9fb8d2dde7e437e5092c828ba8be2d13930c0761c20e78e31dab
  https://github.com/WillAbides/semver-next/releases/download/v2.1.0/semver-next_2.1.0_linux_amd64.tar.gz: 432af06c014d53e4436344343c4a46a20ea222ef9df2e11a52f7fddc917f9df8
  https://github.com/WillAbides/semver-next/releases/download/v2.1.0/semver-next_2.1.0_windows_amd64.tar.gz: a53be2dba639c553556aaf2a3833f633fc60d0c576e6bea89ab959ab1a230c2b
  https://github.com/WillAbides/semver-prev/releases/download/v0.0.1/semver-prev_0.0.1_darwin_amd64.tar.gz: de2902df5f99e6db91b143199446ccf9c7bdacd37980fca55f71e2da35211d0f
  https://github.com/WillAbides/semver-prev/releases/download/v0.0.1/semver-prev_0.0.1_darwin_arm64.tar.gz: 367eaccc368bec6119d47cc78d0ad743cc8709dc1900e8f170c5314418c3a14e
  https://github.com/WillAbides/semver-prev/releases/download/v0.0.1/semver-prev_0.0.1_linux_amd64.tar.gz: 1c1ab5926e9548659bdc1786cf1da9f62f80ae5314c5ccdf71123767e4f4da1d
  https://github.com/WillAbides/semver-prev/releases/download/v0.0.1/semver-prev_0.0.1_windows_amd64.tar.gz: 31bc3527ad74cdfda9d5868287141f44e72e8fbd1709c4f6af05205f9eb8bb8b
  https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_linux_amd64.tar.gz: 9fe05f43a11a7bf8eacf731422452d1997e6708d4160ef0efcb13c103320390e
  https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_macOS_amd64.zip: e116d0f9c310450482cdcd7f4d2d1c7c4cab8d4f025a340260ce3f15329c5145
  https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_macOS_arm64.zip: 38ca9a355376abd1475362cf8b3cacf2a757198fe5fe70349cb1767666abacc6
  https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_windows_amd64.zip: 031eb343ebff6f8cc712d58d79267ee00b0c61b37d6698927161daae895044c6
  https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64: af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44
  https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64: 5c0a0a3ea600f302ee458b30317425dd9632d1ad8882259fcaf4e9b868b2b1ef
  https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe: a51d36968dcbdeabb3142c6f5cf9b401a65dc3a095f3144bd0c118d5bb192753
