version: "2"
linters:
  enable:
    - gocritic
    - gocyclo
    - gosec
    - revive
    - unconvert
  settings:
    errcheck:
      check-blank: true
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - style
        - diagnostic
        - performance
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
      - path: (.+)\.go$
        text: 'G204: Subprocess launched with a potential tainted input or cmd arguments'
      - path: (.+)\.go$
        text: 'G304: Potential file inclusion via variable'
formatters:
  enable:
    - gofumpt
    - gci
