project_name: release-train
gomod:
  proxy: true
builds:
  - goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -w -X main.version={{.Version}}'
    flags: '-trimpath'
    mod_timestamp: '{{.CommitTimestamp}}'
    main: .
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  disable: true
