name: release-train
description: release-train keeps a-rollin' down to San Antone
branding:
  icon: send
  color: yellow
inputs:
  check-pr-labels:
    description: |-
      Instead of releasing, check that the PR has a label indicating the type of change.

      Only literal 'true' will be treated as true.
    default: ${{ github.event_name == 'pull_request' }}
  labels:
    description: |-
      PR label alias in the form of "<alias>=<label>" where <label> is a canonical label.

      One value per line.
  checkout-dir:
    description: The directory where the repository is checked out.
    default: ${{ github.workspace }}
  ref:
    description: git ref.
    default: ${{ github.ref }}
  github-token:
    description: 'The GitHub token to use for authentication. Must have `contents: write` permission if creating a release or tag.'
    default: ${{ github.token }}
  create-tag:
    description: |-
      Whether to create a tag for the release. Implies create-tag.

      Only literal 'true' will be treated as true.
  create-release:
    description: |-
      Whether to create a release. Implies create-tag.

      Only literal 'true' will be treated as true.
  tag-prefix:
    description: The prefix to use for the tag.
    default: v
  v0:
    description: "Assert that current major version is 0 and treat breaking changes as minor changes. \nErrors if the major version is not 0.\n\n\nOnly literal 'true' will be treated as true."
  initial-release-tag:
    description: The tag to use if no previous version can be found. Set to "" to cause an error instead.
    default: v0.0.0
  pre-release-hook:
    description: |
      Command to run before creating the release. You may abort the release by exiting with a non-zero exit code.

      Exit code 0 will continue the release. Exit code 10 will skip the release without error. Any other exit code will
      abort the release with an error.

      You may provide custom release notes by writing to the file at `$RELEASE_NOTES_FILE`:

      ```
        echo "my release notes" > "$RELEASE_NOTES_FILE"
      ```

      You can update the git ref to be released by writing it to the file at `$RELEASE_TARGET`:

      ```
        # ... update some files ...
        git commit -am "prepare release $RELEASE_TAG"
        echo "$(git rev-parse HEAD)" > "$RELEASE_TARGET"
      ```

      If you create a tag named $RELEASE_TAG, it will be used as the release target instead of either HEAD or the value
      written to $RELEASE_TARGET.

      Any files written to $ASSETS_DIR will be uploaded as release assets.

      The environment variables RELEASE_VERSION, RELEASE_TAG, PREVIOUS_VERSION, FIRST_RELEASE, GITHUB_TOKEN,
      RELEASE_NOTES_FILE, RELEASE_TARGET and ASSETS_DIR will be set.
  validate-go-module:
    description: |-
      Validates that the name of the go module at the given path matches the major version of the release. For example,
      validation will fail when releasing v3.0.0 when the module name is "my_go_module/v2".

      One value per line.
  release-refs:
    description: "Only allow tags and releases to be created from matching refs. Refs can be patterns accepted by git-show-ref. \nIf undefined, any branch can be used.\n\nOne value per line."
  no-release:
    description: |-
      If set to true, this will be a no-op. This is useful for creating a new repository or branch that isn't ready for
      release yet.

      Only literal 'true' will be treated as true.
outputs:
  previous-ref:
    value: ${{ steps.release.outputs.previous-ref }}
    description: A git ref pointing to the previous release, or the current ref if no previous release can be found.
  previous-version:
    value: ${{ steps.release.outputs.previous-version }}
    description: The previous version on the release branch.
  first-release:
    value: ${{ steps.release.outputs.first-release }}
    description: Whether this is the first release on the release branch. Either "true" or "false".
  release-version:
    value: ${{ steps.release.outputs.release-version }}
    description: The version of the new release. Empty if no release is called for.
  release-tag:
    value: ${{ steps.release.outputs.release-tag }}
    description: The tag of the new release. Empty if no release is called for.
  change-level:
    value: ${{ steps.release.outputs.change-level }}
    description: The level of change in the release. Either "major", "minor", "patch" or "none".
  created-tag:
    value: ${{ steps.release.outputs.created-tag }}
    description: Whether a tag was created. Either "true" or "false".
  created-release:
    value: ${{ steps.release.outputs.created-release }}
    description: Whether a release was created. Either "true" or "false".
  pre-release-hook-output:
    value: ${{ steps.release.outputs.pre-release-hook-output }}
    description: The stdout of the pre_release_hook. Empty if pre_release_hook is not set or if the hook returned an exit other than 0 or 10.
  pre-release-hook-aborted:
    value: ${{ steps.release.outputs.pre-release-hook-aborted }}
    description: Whether pre_release_hook issued an abort by exiting 10. Either "true" or "false".
runs:
  using: composite
  steps:
    - id: release
      shell: sh
      working-directory: ${{ inputs.checkout_dir }}
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        INPUT_CHECK_PR_LABELS: ${{ inputs.check-pr-labels }}
        INPUT_LABELS: ${{ inputs.labels }}
        INPUT_CHECKOUT_DIR: ${{ inputs.checkout-dir }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_CREATE_TAG: ${{ inputs.create-tag }}
        INPUT_CREATE_RELEASE: ${{ inputs.create-release }}
        INPUT_TAG_PREFIX: ${{ inputs.tag-prefix }}
        INPUT_V0: ${{ inputs.v0 }}
        INPUT_INITIAL_RELEASE_TAG: ${{ inputs.initial-release-tag }}
        INPUT_PRE_RELEASE_HOOK: ${{ inputs.pre-release-hook }}
        INPUT_VALIDATE_GO_MODULE: ${{ inputs.validate-go-module }}
        INPUT_RELEASE_REFS: ${{ inputs.release-refs }}
        INPUT_NO_RELEASE: ${{ inputs.no-release }}
      run: |-
        ACTION_DIR="${{ github.action_path }}"
        if [ -z "$RELEASE_TRAIN_BIN" ]; then
          "$ACTION_DIR"/script/bindown -q install release-train --allow-missing-checksum
          RELEASE_TRAIN_BIN="$ACTION_DIR"/bin/release-train
        fi

        "$RELEASE_TRAIN_BIN" action run
