name: release-train
description: hop on the release train
branding:
  icon: send
  color: yellow

inputs:
  check_pr_labels:
    description: |
      Instead of releasing, check that the PR has a label indicating the type of change.  Only literal 'true' will be treated as true.

    default: ${{ github.event_name == 'pull_request' }}

  checkout_dir:
    description: The directory where the repository is checked out.
    default: ${{ github.workspace }}

  ref:
    description: The branch or tag to release.
    default: ${{ github.ref }}

  github_token:
    description: |
      The GitHub token to use for authentication. Must have `contents: write` permission if creating a release or tag.
    default: ${{ github.token }}

  create_tag:
    description: Whether to create a tag for the release. Only literal 'true' will be treated as true.

  create_release:
    description: |
      Whether to create a release. Only literal 'true' will be treated as true.
      
      Implies `create_tag`.

  tag_prefix:
    description: |
      The prefix to use for the tag. Defaults to `v`.
    default: v

  initial_release_tag:
    description: |
      The tag to use if no previous version can be found.
      
      Set to empty string to disable cause it to error if no previous version can be found.
    default: v0.0.0

  pre_release_hook:
    description: |
      Command to run before creating the release. You may abort the release by exiting with a non-zero exit code.
      
      Exit code 0 will continue the release. Exit code 10 will skip the release without error. Any other exit code will
      abort the release with an error.
      
      You may provide custom release notes by writing to the file at `$RELEASE_NOTES_FILE`:
      ```
      echo "my release notes" > "$RELEASE_NOTES_FILE"
      ```
      
      The environment variables `RELEASE_VERSION`, `RELEASE_TAG`, `PREVIOUS_VERSION`, `FIRST_RELEASE`, `GITHUB_TOKEN`,
      and `RELEASE_NOTES_FILE` will be set.

  post_release_hook:
    description: |
      Command to run after the release is complete. This is useful for adding artifacts to your release.
      
      The environment variables `RELEASE_VERSION`, `RELEASE_TAG`, `PREVIOUS_VERSION`, `FIRST_RELEASE` and `GITHUB_TOKEN` 
      will be set.

  validate_go_module:
    description: |
      Validates that the name of the go module at the given path matches the major version of the release. For example,
      validation will fail when releasing v3.0.0 when the module name is `my_go_module/v2`.
      
      The path provided must be relative to inputs.checkout_dir.
      
      Release train uses whatever version of go is in PATH. If you need to use a specific version of go, you can use
      `WillAbides/setup-go-faster` to install it.

  no_release:
    description: |
      If set to true, this will be a no-op. This is useful for creating a new repository or branch that isn't ready for
      release yet.
      
      Only literal 'true' will be treated as true.

outputs:
  previous_ref:
    value: ${{ steps.release.outputs.previous_ref }}
    description: |
      A git ref pointing to the previous release, or the current ref if no previous release can be found.

  previous_version:
    value: ${{ steps.release.outputs.previous_version }}
    description: |
      The previous version on the release branch.

  first_release:
    value: ${{ steps.release.outputs.first_release }}
    description: |
      Whether this is the first release on the release branch. Either "true" or "false".

  release_version:
    value: ${{ steps.release.outputs.release_version }}
    description: |
      The version of the new release. Empty if no release is called for.

  release_tag:
    value: ${{ steps.release.outputs.release_tag }}
    description: |
      The tag of the new release. Empty if no release is called for.

runs:
  using: composite
  steps:

    - id: check_pr_labels
      if: ${{ inputs.check_pr_labels == 'true' }}
      shell: sh
      working-directory: ${{ inputs.checkout_dir }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GH_TOKEN: ${{ inputs.github_token }}
        NO_RELEASE: ${{ inputs.no_release }}
      run: |
        "${{ github.action_path }}"/src/check_pr_labels

    - id: release
      if: ${{ inputs.check_pr_labels != 'true' }}
      shell: sh
      working-directory: ${{ inputs.checkout_dir }}
      env:
        REF: ${{ inputs.ref }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CREATE_TAG: ${{ inputs.create_tag }}
        CREATE_RELEASE: ${{ inputs.create_release }}
        TAG_PREFIX: ${{ inputs.tag_prefix }}
        INITIAL_RELEASE_TAG: ${{ inputs.initial_release_tag }}
        PRE_RELEASE_HOOK: ${{ inputs.pre_release_hook }}
        POST_RELEASE_HOOK: ${{ inputs.post_release_hook }}
        VALIDATE_GO_MODULE: ${{ inputs.validate_go_module }}
        NO_RELEASE: ${{ inputs.no_release }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        "${{ github.action_path }}"/src/release
