#!/bin/bash
#/ script/check-module-version checks that this module's name works with the given tag.
#/ It assumes that <tag> will always be a valid semantic version prefixed with v.
#/
#/ Usage: script/check-module-version <module name> <tag>

set -e

[ "$#" -eq 2 ] || {
  grep '^#/' < "$0" | cut -c 4- >&2
  exit 1
}

   mod_name="$1"
   version="${2#v}"
   major_version="${version%%.*}"
  if [ "$major_version" -gt 1 ]; then
    if [[ $mod_name != */v"$major_version" ]]; then
      echo "module name $mod_name is not compatible with version $version" >&2
      exit 1
  fi
elif   [[ $mod_name == */v[[:digit:]] ]]; then
      echo "module name $mod_name is not compatible with version $version" >&2
      exit 1
fi
