#!/bin/bash
#/ script/check-module-version checks that this module's name works with the given tag.
#/ It assumes that <tag> will always be a valid semantic version prefixed with v.
#/
#/ Usage: script/check-module-version <module name> <tag>

set -e

[ "$#" -eq 2 ] || {
  grep '^#/' < "$0" | cut -c 4- >&2
  exit 1
}

MOD_NAME="$1"
tmp_VERSION="${2#v}"
MAJOR_VERSION="${tmp_VERSION%%.*}"
if [ "$major_version" -gt 1 ]; then
  if [[ $MOD_NAME != */v"$major_version" ]]; then
    echo "module name $MOD_NAME is not compatible with version $version" >&2
    exit 1
  fi
elif [[ $MOD_NAME == */v[[:digit:]] ]]; then
  echo "module name $MOD_NAME is not compatible with version $version" >&2
  exit 1
fi
