#!/bin/sh
#/ script/deadcode - checks for unused code

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

VERSION="v0.34.0"

GOBIN="$(pwd)/bin" go install golang.org/x/tools/cmd/deadcode@"$VERSION"

bin/deadcode -test -generated ./...
