#!/bin/sh

set -ex

REPO_DIR="$(CDPATH="" cd -- "$(dirname -- "$0")/.." && pwd -P)"

"$REPO_DIR"/script/bindown -q install gh

echo CREATE_RELEASE="$CREATE_RELEASE"
echo CREATE_TAG="$CREATE_TAG"
echo RELEASE_TAG="$RELEASE_TAG"

if [ -n "$RELEASE_NOTES" ] && [ -z "$CREATE_RELEASE" ]; then
  CREATE_RELEASE=1
fi

if [ -n "$CREATE_RELEASE" ] && [ -z "$CREATE_TAG" ]; then
  CREATE_TAG=1
fi

if [ -z "$CREATE_TAG" ]; then
  exit 0
fi

git tag "$RELEASE_TAG" "$REF"
git push origin "$RELEASE_TAG"

if [ -z "$CREATE_RELEASE" ]; then
  exit 0
fi
