#!/bin/sh

set -e

ACTION_DIR="$(CDPATH="" cd -- "$(dirname -- "$0")/.." && pwd -P)"

if [ -n "$NO_RELEASE_FILE" ] && [ -f "$NO_RELEASE_FILE" ]; then
  echo "$NO_RELEASE_FILE exists, exiting" >&2
  exit 0
fi

"$ACTION_DIR"/src/bindown -q install jq gh semver-next
export PATH="$ACTION_DIR/bin:$PATH"

if [ "$GITHUB_EVENT_NAME" != "pull_request" ]; then
  echo "check_pr_labels is only valid on pull_request events" >&2
  exit 1
fi

WANT_LABELS="$(semver-next --show-labels | jq -r 'keys[]')"

PR_NUMBER="$(jq -r .pull_request.number "$GITHUB_EVENT_PATH")"

LABELS="$(gh pr view "$PR_NUMBER" -R "$GITHUB_REPOSITORY" --json labels --jq '.labels[].name')"

# if any of LABELS are in WANT_LABELS, exit 0
for LABEL in $LABELS; do
  if echo "$WANT_LABELS" | grep -qFx "$LABEL"; then
    exit 0
  fi
done

echo "PR must have one of the following labels: $WANT_LABELS" >&2
exit 1
