#!/bin/sh

set -e

REPO_DIR="$(CDPATH="" cd -- "$(dirname -- "$0")/.." && pwd -P)"

"$REPO_DIR"/src/bindown -q install semver-prev

set -- --ref="$REF"
[ -z "$TAG_PREFIX" ] || set -- "$@" --prefix="$TAG_PREFIX"
[ -z "$DEFAULT_PREVIOUS_VERSION" ] || set -- "$@" --fallback="${TAG_PREFIX}${DEFAULT_PREVIOUS_VERSION}"

PREV_REF="$("$REPO_DIR"/bin/semver-prev "$@")"

# trim TAG_PREFIX from PREV_REF
PREV_VERSION="${PREV_REF#$TAG_PREFIX}"

FIRST_RELEASE=false
if ! git rev-parse --quiet --verify "$PREV_REF" >/dev/null; then
  FIRST_RELEASE=true
  PREV_REF="$(git rev-parse "$REF")"
fi

echo version="$PREV_VERSION"
echo ref="$PREV_REF"
echo first_release="$FIRST_RELEASE"
