#!/bin/sh

set -e

ACTION_DIR="$(CDPATH="" cd -- "$(dirname -- "$0")/.." && pwd -P)"

if [ "$NO_RELEASE" = "true" ]; then
  echo "NO_RELEASE is $NO_RELEASE, skipping release" >&2
  exit 0
fi

if [ -z "$RELEASE_TRAIN_BIN" ]; then
  "$ACTION_DIR"/src/bindown -q install release-train
  RELEASE_TRAIN_BIN="$ACTION_DIR"/bin/release-train
fi

set -- release "$GITHUB_REPOSITORY" \
  --ref "$REF" \
  --initial-tag "$INITIAL_RELEASE_TAG" \
  --pre-release-hook "$PRE_RELEASE_HOOK" \
  --post-release-hook "$POST_RELEASE_HOOK"

[ "$CREATE_TAG" != "true" ]     || set -- "$@" --create-tag
[ "$CREATE_RELEASE" != "true" ] || set -- "$@" --create-release
[ -z "$TAG_PREFIX" ]            || set -- "$@" --tag-prefix "$TAG_PREFIX"
[ -z "$VALIDATE_GO_MODULE" ]    || set -- "$@" --go-mod-file "$VALIDATE_GO_MODULE"
[ -z "$RUNNER_TEMP" ]           || set -- "$@" --tempdir "$RUNNER_TEMP"

"$ACTION_DIR"/bin/release-train "$@"
