#!/bin/sh

set -e

ACTION_DIR="$(cd -- "$(dirname -- "$0")/.." && pwd)"

build() {
  cd "$ACTION_DIR"

  # TODO: use bindown to install from release artifacts when running in an action that points to a release tag.

  # If go is in path and is at least version 1.20, use it.
  if command -v go > /dev/null 2>&1; then
    if go version | grep -q 'go1\.[2-9][0-9]\+'; then
      go build -o bin/release-train .
      return
    fi
  fi

  # Install go with bindown. This takes a bit longer.
  ./src/bindown -q install go

  # Clear out the environment variables so we don't end up having
  # to debug weird issues in actions.
  GOROOT="" \
    GOPATH="" \
    GOENV="" \
    GOCACHE="" \
    GOMODCACHE="" \
    GOPROXY="" \
    GO111MODULE="" \
    GOFLAGS="" \
    GOSUMDB="" \
    GOPRIVATE="" \
    GONOPROXY="" \
    GONOSUMDB="" \
    CGO_ENABLED="0" \
    ./bin/go build -o bin/release-train .
}

build

"$ACTION_DIR"/bin/release-train "$@"
