#!/bin/sh

set -e

[ -n "$VALIDATE_GO_MODULE" ] || exit 0

cd -- "$VALIDATE_GO_MODULE"
MODULE_VERSION_SUFFIX="$(go list -m | grep -o '/v[0-9][0-9]*$' || true)"

MAJOR_VERSION="${RELEASE_VERSION%%.*}"

if [ "$MAJOR_VERSION" -ge 2 ] && [ "$MODULE_VERSION_SUFFIX" != "/v$MAJOR_VERSION" ]; then
  echo "module version suffix must be /v$MAJOR_VERSION"
  exit 1
elif [ "$MAJOR_VERSION" -lt 2 ] && [ -n "$MODULE_VERSION_SUFFIX" ]; then
  echo "Module name must not end with /v[0-9][0-9]*"
  exit 1
fi
