name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version: '1.20.x'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: go-${{ runner.os }}-${{ hashFiles('go.*', '*.go', '.github/workflows/ci.yaml', 'script/*', 'src/*' ,'.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: go-${{ runner.os }}-
      - uses: tibdex/github-app-token@v1.8.0
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASER_APP_ID }}
          private_key: ${{ secrets.RELEASER_APP_KEY }}
      - name: config
        run: |
          git config --local user.name '${{ github.actor }}'
          git config --local user.email '${{ github.actor }}@users.noreply.github.com'
          go build -o bin/release-train .
          echo RELEASE_TRAIN_BIN="$(pwd)"/bin/release-train >> "$GITHUB_ENV"
      - run: script/cibuild
      - id: release-train
        uses: './'
        with:
          create_release: true
          validate_go_module: go.mod
          pre_release_hook: |
            script/bindown dependency update-vars release-train \
              --set version="$RELEASE_VERSION" \
              --skipchecksums
            if ! git diff --quiet .bindown.yaml; then
              exit 10
            fi
      - if: steps.release-train.outputs.created_release == 'true'
        name: goreleaser
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git status
          script/bindown -q install goreleaser
          bin/goreleaser release --clean
      - if: steps.release-train.outputs.pre_release_hook_aborted == 'true'
        name: create release pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          add-paths: ".bindown.yaml"
          commit-message: "prepare to release ${{ steps.release-train.outputs.release_tag }}"
          branch: "prepare-release"
          delete-branch: true
          title: "prepare to release ${{ steps.release-train.outputs.release_tag }}"
          body: "prepare to release ${{ steps.release-train.outputs.release_tag }}"
          labels: "semver:nochange"
