name: ci
on:
  push:
    branches: [ '*' ]
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version: '1.20.x'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: go-${{ runner.os }}-${{ hashFiles('go.*', '*.go', '.github/workflows/ci.yaml', 'script/*', 'action/*' ,'.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: go-${{ runner.os }}-
      - uses: tibdex/github-app-token@v1.8.0
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASER_APP_ID }}
          private_key: ${{ secrets.RELEASER_APP_KEY }}
      - name: config
        run: |
          git config --local user.name '${{ github.actor }}'
          git config --local user.email '${{ github.actor }}@users.noreply.github.com'
          go build -o bin/release-train .
          echo RELEASE_TRAIN_BIN="$(pwd)"/bin/release-train >> "$GITHUB_ENV"
      - run: script/cibuild
      - id: release-train
        uses: './'
        with:
          create_release: true
          validate_go_module: go.mod
          release_refs: refs/heads/v[0-9],refs/heads/v[0-9][0-9],main
          pre_release_hook: |
            script/bindown dependency update-vars release-train \
              --set version="$RELEASE_VERSION" \
              --skipchecksums
            
            # abort release if .bindown.yaml changed
            git diff --quiet .bindown.yaml || exit 10
            
            script/bindown install goreleaser
            git tag "$RELEASE_TAG"
            bin/goreleaser release --clean --skip-publish
            cp dist/checksums.txt dist/release-train_*.tar.gz "$ASSETS_DIR"
      - if: steps.release-train.outputs.pre_release_hook_aborted == 'true'
        name: create release pr
        id: create-release-pr
        # v5.0.1
        uses: peter-evans/create-pull-request@284f54f989303d2699d373481a0cfa13ad5a6666
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          add-paths: ".bindown.yaml"
          commit-message: "prepare to release ${{ steps.release-train.outputs.release_tag }}"
          branch: "prepare-release"
          delete-branch: true
          title: "prepare to release ${{ steps.release-train.outputs.release_tag }}"
          body: "prepare to release ${{ steps.release-train.outputs.release_tag }}"
          labels: "semver:nochange"
      - if: steps.create-release-pr.outputs.pull-request-number
        name: auto-merge release pr
        env:
          GH_TOKEN: "${{ steps.generate-token.outputs.token }}"
        run: gh pr merge --merge --auto ${{ steps.create-release-pr.outputs.pull-request-number }}
