name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version: '1.20.x'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: go-${{ runner.os }}-${{ hashFiles('go.*', '*.go', '.github/workflows/ci.yaml', 'script/*', 'src/*' ,'.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: go-${{ runner.os }}-
      - uses: tibdex/github-app-token@v1.8.0
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASER_APP_ID }}
          private_key: ${{ secrets.RELEASER_APP_KEY }}
      - name: config
        run: |
          git config --local user.name '${{ github.actor }}'
          git config --local user.email '${{ github.actor }}@users.noreply.github.com'
          go build -o bin/release-train .
          echo RELEASE_TRAIN_BIN="$(pwd)"/bin/release-train >> "$GITHUB_ENV"
      - run: script/cibuild
      - id: release-train
        uses: './'
        with:
          create_release: true
          validate_go_module: go.mod
          pre_release_hook: |
            script/bindown dependency update-vars release-train \
              --set version="$RELEASE_VERSION" \
              --skipchecksums
            if git diff --quiet .bindown.yaml; then
              echo "no changes to .bindown.yaml"
              exit 0
            fi
            git add .bindown.yaml
            git commit -m "prepare to release $RELEASE_TAG"
            echo "$(git rev-parse HEAD)" > "$RELEASE_TARGET"
      - if: steps.release-train.outputs.created_release == 'true'
        name: goreleaser
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git status
          script/bindown -q install goreleaser
          bin/goreleaser release --clean
      - if: steps.release-train.outputs.created_release == 'true'
        name: update release-train
        run: |
          TOKEN="${{ steps.generate-token.outputs.token }}"
          git push "https://x-access-token:${TOKEN}@${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" main
