name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: script/lint
      - run: script/generate --check
