name: rel test
on:
  push:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - labeled
      - unlabeled
jobs:
  rel:
    name: rel
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
           go-version: '1.20.x'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-rel-${{ github.event_name }}-${{ hashFiles('go.*', '.github/workflows/ci.yaml', 'script/*', '.bindown.yaml', '.goreleaser.yaml') }}
          restore-keys: ${{ runner.os }}-go-rel-${{ github.event_name }}-
      - run: echo "RELEASE_TRAIN_BIN="$(pwd)"/bin/release-train >> $GITHUB_ENV
      - uses: './'
        id: local-action
        with:
          create_release: true
          pre_release_hook: |
            echo LGTM
            exit 0
          post_release_hook: |
            echo all done
            exit 0
      - run: |
          echo "local-action outputs:"
          echo '${{ toJSON(steps.local-action.outputs) }}'
