name: rel test
on:
  push:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - labeled
      - unlabeled
jobs:
  rel:
    name: rel
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # composite action from this repo
      - uses: './'
        id: local-action
        with:
          create_release: true
          pre_release_hook: |
            echo LGTM
            exit 0
          post_release_hook: |
            echo all done
            exit 0
      - run: |
          echo "local-action outputs:"
          echo '${{ toJSON(steps.local-action.outputs) }}'
