name: version-labels
on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - labeled
      - unlabeled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  version-labels:
    name: version-labels
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write
    steps:
      # tag v4.0.0: https://github.com/mheap/github-action-required-labels/releases/tag/v4.0.0
      - uses: mheap/github-action-required-labels@422e4c352ef83db91089e6acfbf09d8725e08abc
        with:
          mode: minimum
          count: 1
          labels: |
            breaking, breaking change, bug, enhancement, patch, semver:patch, semver:minor, minor, major, semver:major, no change, semver:none, semver:no change, semver:nochange, semver:skip
          message: |
            This PR cannot be merged until it has at least one label indicating the type of change it is.
          add_comment: true
